### PR TITLE
chore(bundle): UMD bundle for aurelia

### PR DESCRIPTION
**Pull request by bigopon**
- UMD bundle so aurelia can be used in traditional way without too much hassle

@EisenbergEffect I'm not sure if I should include a default loader (say `esm-loader`) or let folk decide what loader they want to use and create instance of Aurelia with it. like `new Aurelia(new RequireJsLoader())`

Some number:
- UMD bundle size: 557KB (without router ~= 464KB)
- minified: 254KB (without router ~= 218KB)
- gzip: 68KB (without router ~= 57KB)

---

`index.html` umd way:
```html
<body>
  <script src='./aurelia-framework.bundle.min.js'></script>
  <script>
    const aurelia = new au.Aurelia(new EsmLoader())
    aurelia
      .use
        .standardConfiguration()
        .developmentLogging();
    aurelia.start().then(() => aurelia
      .setRoot(
        class App {
          static get $view() {
            return '<template>${message}</template>'
          }

          constructor() {
            this.message = 'Hello world';
          }
        },
        document.body
    ));
  </script>
</body>
```

We may want also provide a esm bundle, so folk can write code in following way:
```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>GistRun</title>
</head>
<body>Loading...</body>
<script type="module">
  import { Aurelia } from './aurelia.esm.js';
  const app = new Aurelia(new EsmLoader());
  app.use.standardConfiguration();
  app.start().then(() => app.setRoot(
    class ShellViewModel {
      static get $view() { return '<template>Hello, world!</template>' };
    },
    document.body
  ));
</script>
</html>
```

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Nice work @bigopon Before I merge, I just want to check something with @jdanyow Is this going to affect the PR we just sent to fix up our dbmoster benchmark?

**Comment by jdanyow** [comment]
@EisenbergEffect not sure, I can check next week (in Shanghai for work without my personal laptop). Here's the repo if anyone can get to this before me:
https://github.com/mathieuancelin/js-repaint-perfs

I just found out there's a more massive issue coming... [rawgit is being shut down](https://rawgit.com/).

When this happens, any gist created by forking the [aurelia gist](https://gist.run/?id=7542e061bc940cde506b) prior to this [April 11, 2016 change](https://gist.github.com/jdanyow/7542e061bc940cde506b/revisions#diff-eacf331f0ffc35d4b482f1d15a887d3b) will stop working. The dbmonster demo is also using rawgit.

**Comment by EisenbergEffect** [comment]
Thanks for the heads up!

**Comment by bigopon** [comment]
@EisenbergEffect @jdanyow I've adjusted it a bit. Now it comes with following combinations:

| | ESM | UMD |
|-|-|-
| core | 446KB <br> minified: 244KB <br> min + gz: 60.1KB | 476KB <br> minified: 218KB <br> min + gz: 57KB
| core + router | 523KB <br> minified: 285KB <br> min + gz: 71.5KB  | 557KB <br> minified: 254KB <br> min + gz: 67.7KB

**Comment by bigopon** [comment]
@jdanyow Why won't the forks work? It's quite an issue as a lot of our PR examples, bug reports won't be easily playable.

**Comment by jdanyow** [comment]
@bigopon I think most forks will work because they don't use rawgit. 

Forks of the [aurelia gist](https://gist.run/?id=7542e061bc940cde506b) prior to [:sparkles:**this April 11, 2016 change**:sparkles:](https://gist.github.com/jdanyow/7542e061bc940cde506b/revisions#diff-eacf331f0ffc35d4b482f1d15a887d3b) will stop working because rawgit is used in the gist.

**Comment by bigopon** [comment]
I've added esm loader https://github.com/bigopon/aurelia-loader-esm, and some example how to use it. This is example `index.html`:

```html
<body>
  <script src='./aurelia_router.umd.min.js'></script>
  <script>
    const aurelia = new au.Aurelia()
    aurelia
      .use
        .standardConfiguration()
        .developmentLogging();
    aurelia.start().then(() => aurelia.setRoot('/app.js', document.body));
  </script>
</body>
```

With the following folder structure:

```
📂dist
├ 📂components
│  ├ foo.js
│  └ foo.html
├ 📂routes
│  ├ page.js
│  └ page.html
├ app.js
├ app.html
├ index.html
└ aurelia_router.umd.min.js
    
```

Notice app root `/app.js` or the router config, `{ route: '', moduleId: '/routes/home.js' }`, we can go for full path to JS file. `html` template is automatically loaded accordingly. Everything feels very natural and standard compliant.

@EisenbergEffect @jdanyow

**Comment by Vheissu** [comment]
@bigopon Thank you Santa.

**Comment by plwalters** [comment]
@jdanyow  FWIW they have a fast change available from rawgit to jsdelivr -

https://www.jsdelivr.com/rawgit

**Comment by EisenbergEffect** [comment]
@bigopon I've merged this PR, but I think there's some follow-up we may want to do:

* We should get the ESM loader stuff into an official repo. Is it small enough to put in `loader-default` or should we spin up a new repo at `loader-esm`?
* Can you look into us getting these builds on a CDN?
* Can you take a look at the PR @jdanyow sent to DBMonster? https://github.com/mathieuancelin/js-repaint-perfs/pull/133 It should continue to work but it would be great if we can get that updated to use the new builds via CDN.
* Let's get an official CodeSandbox.io sandbox setup so that it can be used for our site tutorials. Once we have that, I can start incorporating it into the site's homepage and working on the new tutorials. We can also reach back out to CodeSandbox to get Aurelia in their official list. They expressed via Twitter that they'd be interested in getting it into the next round.

**Comment by bigopon** [comment]
@EisenbergEffect Can you create a repo for `loader-esm` and give me push right? I'll handle it and ping you when it's complete. About cdn, I'll have a look, never done that before. I'm also looking at codesandbox integration.

**Comment by EisenbergEffect** [comment]
Ok, repo is ready for you: https://github.com/aurelia/loader-esm
Keep me posted on the sandbox and cdn tasks. Awesome work so far! This will be huge for the community.

**Pull request merged**
