### PR TITLE
feat(all): add quick start/enhance helpers to enable 1 line usage

### PR DESCRIPTION
**Pull request by bigopon**

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Very nice. However, should any of this be built back into the framework library? or do you think this all only really applies in the script tag scenario?

**Comment by bigopon** [comment]
@EisenbergEffect I think we could, but I'm not sure where it should resides though. static method or just a loose function in framework module?

**Comment by EisenbergEffect** [comment]
Actually, I'm not sure we should add it there. There's some code that's very similar to this in the bootstrapper already. Is this needed because script file only builds don't use the bootstrapper module?

**Comment by bigopon** [comment]
@EisenbergEffect This is mostly to reduce boilerplate, while bootstrapper is more of setting up platform/environment for application startup. I guess it can take some extra stuff, but we can try with script first before adding something like this to bootstrapper

**Comment by EisenbergEffect** [comment]
That sounds reasonable. @bigopon Is this ready to go then?

**Comment by bigopon** [comment]
@EisenbergEffect Yes, it's ready for final review. If needed, we can also release a beta to test the water. your strategy 👍

**Comment by EisenbergEffect** [comment]
Looks good. What was my procedure for release on this library again? Do I just need to build and push to npm and GH like normal?

**Comment by bigopon** [comment]
@EisenbergEffect Yes, only need to run `npm run bundle`

**Comment by EisenbergEffect** [comment]
@bigopon I'm fine with just releasing it as is rather than doing a beta. Do you think we're ready for release? I just merged another of your PRs, so I wanted to make sure you felt it was ready for 1.4.0 and that you weren't cooking up anything else right away.

**Pull request merged**
