### PR TITLE
feat(all): emit build to example. Add jsdelivr and browser fields

### PR DESCRIPTION
**Pull request by bigopon**
@EisenbergEffect You will need to run build in at least 2 repos: `templating` & `templating-binding` to add the most recent fixes. And run `npm run bundle` inside this repo for a release. It's ready for `unpkg`. For `jsdelivr`, I think we will need to tag release before it can work properly, as their example for github is something like this:
```
https://cdn.jsdelivr.net/gh/jquery/jquery@3.2.1/
```
If we release this to npm, then probably no need for git tag.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@bigopon I'd like to request one addition to this PR. Can you add a section to the README which describes all the file outputs of the build process and what each one is?

**Comment by bigopon** [comment]
@EisenbergEffect I've added the basic of what I think enough. Please have some modification as you see fit.

**Comment by bigopon** [comment]
@EisenbergEffect Note that I'm installing from github repos, not npm. Not sure if it should be changed to npm.

**Comment by EisenbergEffect** [comment]
Perfect. Thanks @bigopon !

**Pull request merged**
