### PR TITLE
feat(cdn-unpkg): add unpkg field in package.json

### LINKED ISSUE #14: Add an unpkg field to package.json
A bare URL returns the `browser` linked file, but we should really support the official `unpkg` entry.

Should we also be referencing the .min version?

Obviously we can do this by specifying the full path:
`https://unpkg.com/aurelia-script@1.2.0/dist/aurelia_router.umd.min.js`
but if we're creating blogs and samples referring to the short-version
`https://unpkg.com/aurelia-script@1.2.0`
then we might want to use the 66KB bundle instead.

### PR DESCRIPTION
**Pull request by bigopon**
Thanks to @jsobell for the suggestion
resolves #14 

@EisenbergEffect

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Thanks @bigopon This is also great learning for setting up vNext correctly so that we have it right from day one :)

**Comment by bigopon** [comment]
Yes. vNext is already ready for this. We just need a bit tweak :poke: @fkleuver

**Comment by fkleuver** [comment]
A bit tweak?

**Comment by jsobell** [comment]
Perhaps he means a twit beak? 🐦

**Pull request merged**
